version: "3.9"
services: 
  db:
    image: mysql:8.0
    ports: 
      - "3307:3306"
    environment: 
      MYSQL_DATABASE: "django_db"
      MYSQL_USER: "django_user"
      MYSQL_PASSWORD: "django_pass"
      MYSQL_ROOT_PASSWORD: "django_pass_root"
    volumes: 
      - ./data:/var/lib/mysql
  
  api:
    build: 
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports: 
      - "9800:8000"
    volumes: 
      - ./api:/code
    depends_on: 
      - db
    command: python manage.py runserver 0.0.0.0:8000
