version: "3.6"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  app:
    build:
      context: .
      args:
        DEV: ${DEV}
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./app:/app
      - ../web:/vol/web
      - ../LocalDropbox:/LocalDropbox
      - ../LocalDrive:/LocalDrive
      - ../Working:/Working
      - ../tmp:/var/tmp
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DEBUG=1
      - ALLOWED_HOST=${ALLOWED_HOST}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      - DJANGO_LOG_LEVEL=${DJANGO_LOG_LEVEL}
    depends_on:
      - db

  # celery:
  #   restart: always
  #   build:
  #     context: .
  #   command: celery -A app worker -l DEBUG --beat
  #   volumes:
  #     - ./app:/app
  #   environment:
  #     - DB_HOST=${DB_HOST}
  #     - DB_NAME=${DB_NAME}
  #     - DB_USER=${DB_USER}
  #     - DB_PASS=${DB_PASS}
  #   depends_on:
  #     - db
  #     - redis
  #     - app

  frontend:
    build:
      context: frontend
    command: sh -c "yarn install && yarn dev"
    # command: sh -c "yarn install && yarn build && yarn start"
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    restart: always
    environment:
      - REACT_APP_API_URL=${API_URL}


  nginx:
    depends_on:
      - app
      - frontend
    image: nginx:alpine
    ports:
      - 8880:80
      - 8443:443
    restart: always
    volumes:
      - ./proxy/dev.conf:/etc/nginx/conf.d/default.conf
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf

volumes:
  dev-db-data:
