# Generated by Django 4.0.10 on 2023-05-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermanager',
            name='deadline',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customermanager',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
