# Generated by Django 4.0.10 on 2023-06-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_manager', '0002_customermanager_deadline_customermanager_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermanager',
            name='customer_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customermanager',
            name='editor_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
