# Generated by Django 4.0.10 on 2023-05-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customerCode', models.CharField(max_length=50, unique=True)),
                ('customerName', models.CharField(max_length=255)),
                ('customerEmail', models.EmailField(max_length=255, unique=True)),
                ('customerExpose', models.CharField(max_length=255)),
                ('customerStyle', models.TextField()),
                ('customerDescription', models.TextField()),
                ('customerNamePay', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
