# Generated by Django 4.0.10 on 2023-05-06 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customermanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermanager',
            old_name='customerCode',
            new_name='customer_code',
        ),
        migrations.RenameField(
            model_name='customermanager',
            old_name='customerDescription',
            new_name='customer_description',
        ),
        migrations.RenameField(
            model_name='customermanager',
            old_name='customerEmail',
            new_name='customer_email',
        ),
        migrations.RenameField(
            model_name='customermanager',
            old_name='customerExpose',
            new_name='customer_expose',
        ),
        migrations.RenameField(
            model_name='customermanager',
            old_name='customerName',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='customermanager',
            old_name='customerNamePay',
            new_name='customer_namepay',
        ),
        migrations.RenameField(
            model_name='customermanager',
            old_name='customerStyle',
            new_name='customer_style',
        ),
    ]
