# Generated by Django 4.0.10 on 2023-06-28 00:16

import collections
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_user_address_alter_user_bank_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonUserSetting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('pagination', jsonfield.fields.JSONField(load_kwargs={'object_pairs_hook': collections.OrderedDict})),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
