# Generated by Django 4.0.10 on 2023-04-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmanager',
            name='path',
            field=models.CharField(max_length=520, unique=True),
        ),
        migrations.AlterField(
            model_name='jobstatus',
            name='key',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usersettingjob',
            name='key',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
