# Generated by Django 4.0.10 on 2023-04-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manager', '0002_alter_jobmanager_path_alter_jobstatus_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmanager',
            name='files',
            field=models.JSONField(default={}),
        ),
    ]
