# Generated by Django 4.0.10 on 2023-04-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manager', '0003_jobmanager_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobmanager',
            name='number_of_new_file',
        ),
        migrations.AlterField(
            model_name='jobmanager',
            name='path',
            field=models.CharField(db_index=True, max_length=520),
        ),
    ]
