# Generated by Django 4.0.10 on 2023-04-09 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_manager', '0004_remove_jobmanager_number_of_new_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobmanager',
            name='files',
        ),
    ]
