# Generated by Django 4.0.10 on 2023-04-09 22:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manager', '0005_remove_jobmanager_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmanager',
            name='files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=520), blank=True, default=[], size=None),
        ),
    ]
