# Generated by Django 4.0.10 on 2023-04-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manager', '0007_alter_jobmanager_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettingjob',
            name='value',
            field=models.JSONField(),
        ),
    ]
