# Generated by Django 4.0.10 on 2023-06-11 04:52

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_manager', '0002_customermanager_deadline_customermanager_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_manager', '0008_alter_usersettingjob_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder_path', models.CharField(db_index=True, max_length=520)),
                ('name', models.CharField(db_index=True, max_length=520)),
                ('files', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=520), blank=True, default=list, size=None)),
                ('expose', models.CharField(max_length=255)),
                ('style', models.TextField()),
                ('note', models.TextField(blank=True, null=True)),
                ('deadline', models.TimeField(blank=True, null=True)),
                ('number_sub_job', models.IntegerField(blank=True, null=True)),
                ('customer_price', models.FloatField(blank=True, null=True)),
                ('editor_price', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[['creating', 'Đang tạo Job'], ['new', 'Mới'], ['doing', 'Đang làm'], ['waiting_check', 'Chờ check'], ['checking', 'Đang check'], ['qc_ok', 'QC OK'], ['waiting_edit', 'Chờ sửa'], ['qc_edit', 'QC sửa'], ['qc_editing', 'QC đang sửa'], ['done', 'Sửa xong'], ['approve', 'Hoàn thành']], max_length=50)),
                ('source', models.CharField(choices=[('auto', 'Tạo job tự động'), ('manual', 'Tạo job bằng tay')], max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_manager.customermanager')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
