# Generated by Django 4.0.10 on 2023-06-14 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manager', '0009_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='des_path',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='src_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
