# Generated by Django 4.0.10 on 2023-06-18 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_manager', '0011_jobhistory_job_user_alter_job_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobhistory',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignee_job_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobhistory',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_histories', to='job_manager.job'),
        ),
        migrations.AddField(
            model_name='jobhistory',
            name='status',
            field=models.CharField(choices=[['creating', 'Đang tạo Job'], ['new', 'Mới'], ['doing', 'Đang làm'], ['waiting_check', 'Chờ check'], ['checking', 'Đang check'], ['qc_ok', 'QC OK'], ['waiting_edit', 'Chờ sửa'], ['qc_edit', 'QC sửa'], ['qc_editing', 'QC đang sửa'], ['done', 'Sửa xong'], ['approve', 'Hoàn thành']], default=None, max_length=50),
        ),
    ]
