# Generated by Django 4.0.10 on 2023-06-18 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_manager', '0012_jobhistory_editor_jobhistory_job_jobhistory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobhistory',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_job_histories', to=settings.AUTH_USER_MODEL),
        ),
    ]
