# Generated by Django 4.0.10 on 2023-06-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manager', '0013_jobhistory_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='file_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
