from himalaya import models
# DmNhomdoituong
# DmDoituong

srcDmNhomdoituongs = models.DmNhomdoituong.objects.using('himalaya').all()
desDmNhomdoituongsData = [models.DmNhomdoituong(
    id=item.id,
    loaidoituong=item.loaidoituong,
    manhom=item.manhom,
    tennhom=item.tennhom,
    ghichu=item.ghichu,
    usertao=item.usertao,
    ngaytao=item.ngaytao,
    usersuacuoi=item.usersuacuoi,
    ngaysuacuoi=item.ngaysuacuoi,
) for item in srcDmNhomdoituongs]
models.DmNhomdoituong.objects.using('default').bulk_create(desDmNhomdoituongsData)


srcDmDoituongs = models.DmDoituong.objects.using('himalaya').all()
desDmDoituongsData = [models.DmDoituong(
    id=item.id,
    loaidoituong=item.loaidoituong,
    lacanhan=item.lacanhan,
    id_nhomdoituong_id=item.id_nhomdoituong_id,
    madoituong=item.madoituong,
    tendoituong=item.tendoituong,
    dienthoai=item.dienthoai,
    fax=item.fax,
    email=item.email,
    website=item.website,
    anh=item.anh,
    masothue=item.masothue,
    taikhoannganhang=item.taikhoannganhang,
    gioihancongno=item.gioihancongno,
    ghichu=item.ghichu,
    id_tinhthanh=item.id_tinhthanh,
    ngaysinh_ngaytlap=item.ngaysinh_ngaytlap,
    chiase=item.chiase,
    theodoi=item.theodoi,
    usertao=item.usertao,
    ngaynhap=item.ngaynhap,
    usersuacuoi=item.usersuacuoi,
    ngaysuacuoi=item.ngaysuacuoi,
    id_index=item.id_index,
    theodoivantay=item.theodoivantay,
    id_quanhuyen=item.id_quanhuyen,
    id_nhanvienphutrach=item.id_nhanvienphutrach,
    ngaydoinhom=item.ngaydoinhom,
    diemkhoitao=item.diemkhoitao,
    doanhsokhoitao=item.doanhsokhoitao,
    id_nguoigioithieu=item.id_nguoigioithieu,
    id_nguonkhach=item.id_nguonkhach,
    captai_dkkd=item.captai_dkkd,
    diachi=item.diachi,
    gioitinhnam=item.gioitinhnam,
    nganhang=item.nganhang,
    ngaycapcmtnd_dkkd=item.ngaycapcmtnd_dkkd,
    noicapcmtnd_dkkd=item.noicapcmtnd_dkkd,
    sdt_coquan=item.sdt_coquan,
    sdt_nharieng=item.sdt_nharieng,
    socmtnd_dkkd=item.socmtnd_dkkd,
    thuongtru=item.thuongtru,
    xungho=item.xungho,
    id_quocgia=item.id_quocgia,
    ngaygiaodichgannhat=item.ngaygiaodichgannhat,
    id_nhomcu=item.id_nhomcu,
    tennguonkhach=item.tennguonkhach,
    tennhom=item.tennhom,
    id_donvi=item.id_donvi,
    chucvu=item.chucvu,
    linhvuc=item.linhvuc,
    nghenghiep=item.nghenghiep,
    tenkhac=item.tenkhac,
    diachikhac=item.diachikhac,
    id_trangthai=item.id_trangthai,
    ngaysuatrangthai=item.ngaysuatrangthai,
) for item in srcDmDoituongs]
models.DmDoituong.objects.using('default').bulk_create(desDmDoituongsData)